import { APPOINTMENT_REMINDER, APPOINTMENT_STATUS } from "../config/constants.js";

export function createAppointment(data = {}) {
  return {
    id: data.id ?? "",
    // Mobile-canonical fields (the mobile app reads these names).
    familyId: data.familyId ?? "",
    seniorId: data.seniorId ?? "",
    doctor: data.doctor ?? data.practitionerName ?? "",
    clinic: data.clinic ?? data.location ?? "",
    type: data.type ?? "doctorVisit",
    scheduledAt: data.scheduledAt ?? null,
    durationMinutes: data.durationMinutes ?? 60,
    transportation: data.transportation ?? "none",
    mobileStatus: data.mobileStatus ?? "",
    notifyEnabled: data.notifyEnabled ?? true,
    assignedUserId: data.assignedUserId ?? data.practitionerUserId ?? "",
    assignedDisplayName: data.assignedDisplayName ?? data.practitionerName ?? "",
    assignmentStatus: data.assignmentStatus ?? "",
    // Web fields (kept; aliases of the canonical ones above).
    title: data.title ?? data.practitionerName ?? "",
    date: data.date ?? "",
    time: data.time ?? "",
    endTime: data.endTime ?? "",
    location: data.location ?? data.clinic ?? "",
    notes: data.notes ?? "",
    status: data.status ?? APPOINTMENT_STATUS.SCHEDULED,
    practitionerId: data.practitionerId ?? "",
    practitionerUserId: data.practitionerUserId ?? data.assignedUserId ?? "",
    practitionerEmail: data.practitionerEmail ?? "",
    practitionerName: data.practitionerName ?? data.doctor ?? "",
    reminder: data.reminder ?? APPOINTMENT_REMINDER.DAY_1,
    reminderAt: data.reminderAt ?? null,
    reminderSent: Boolean(data.reminderSent),
    createdBy: data.createdBy ?? "",
    createdByName: data.createdByName ?? "",
    updatedBy: data.updatedBy ?? "",
    updatedByName: data.updatedByName ?? "",
    createdAt: data.createdAt ?? null,
    updatedAt: data.updatedAt ?? null,
    cancelledAt: data.cancelledAt ?? null,
    cancelledBy: data.cancelledBy ?? "",
    cancelledByName: data.cancelledByName ?? "",
    cancelReason: data.cancelReason ?? "",
  };
}
