import {
  ACTIVITY_TYPES,
  AVAILABILITY,
  CARE_CIRCLE_ROLES,
  CARE_HISTORY_KINDS,
  CARE_PLAN_STATUS,
  CARE_STATUS,
  CARE_TASK_CATEGORY,
  CARE_TASK_FREQUENCY,
  CARE_TASK_PRIORITY,
  CARE_TASK_STATUS,
  APPOINTMENT_REMINDER,
  APPOINTMENT_STATUS,
  MEDICATION_DOSE_OUTCOME,
  MEDICATION_FREQUENCY,
  MEDICATION_REMINDER,
  MEDICATION_STATUS,
  CIRCLE_KINDS,
  CIRCLE_STATUS,
  CONVERSATION_TYPES,
  INVITE_STATUS,
  NOTIFICATION_TYPES,
  PROFESSIONAL_TYPES,
  VISIT_STATUS,
} from "../config/constants.js";
import { permissionsForRole } from "../config/care-circle.js";
import { AVAILABILITY_KIND, PROFESSIONAL_KIND } from "../config/scheduling.js";
import { createSenior } from "../models/senior.js";
import { createCareCircleMember, createCareCircleInvite } from "../models/care-circle.js";
import { createScheduleEvent } from "../models/schedule-event.js";
import { createScheduleVisit, createVisitNote, createVisitReport } from "../models/schedule-visit.js";
import { createAvailabilityWindow } from "../models/availability.js";
import { createCarePlan, createCarePlanTask, createCarePlanCompletion } from "../models/care-plan.js";
import { createAppointment } from "../models/appointment.js";
import { appointmentReminderAt } from "../config/appointment.js";
import { createMedication, createMedicationDose } from "../models/medication.js";
import { medicationReminderAt } from "../config/medication.js";
import { createNotification } from "../models/notification.js";
import { createActivity } from "../models/activity.js";
import { createDocument } from "../models/document.js";
import { createConversation } from "../models/conversation.js";
import { createMessage } from "../models/message.js";
import { dateForWeekday } from "../scheduling/calendar.js";

function stampAt(weekday, hours, minutes) {
  const date = new Date(`${dateForWeekday(weekday)}T00:00:00`);
  date.setHours(hours, minutes, 0, 0);
  return date.toISOString();
}

export const mockSenior = createSenior({
  id: "senior-eleanor",
  ownerId: "user-family",
  memberIds: ["user-family", "user-caregiver", "user-practitioner", "user-admin"],
  displayName: "Eleanor Walsh",
  preferredName: "Ellie",
  dateOfBirth: "1942-04-18",
  gender: "female",
  phone: "(410) 555-0114",
  location: "Towson, Baltimore County, MD",
  address: "1 Olympic Place, Towson, MD 21204",
  conditions: ["Hypertension", "Mild osteoarthritis"],
  medications: ["Lisinopril 10mg", "Vitamin D 2000 IU"],
  allergies: ["Penicillin"],
  emergencyContacts: [
    {
      id: "ec-amina",
      name: "Sarah Walsh",
      phone: "(410) 555-0142",
      email: "family@famielda.test",
      relationship: "Daughter",
      isPrimary: true,
    },
    {
      id: "ec-patel",
      name: "Dr. Patel",
      phone: "(410) 555-0198",
      email: "practitioner@famielda.test",
      relationship: "Primary physician",
    },
  ],
  carePreferences: {
    preferredLanguage: "en",
    mobility: "walker",
    diet: "low_sodium",
    communication: "verbal",
    dailyRoutine: "Up by 7:30 for tea before medication. Rest after lunch. Evening news with a light supper.",
    likes: "NPR in the morning, short neighborhood walks, Maryland crab cakes on Sundays.",
    dislikes: "Being rushed in the morning, cold rooms, bright overhead lights at night.",
    notes: "Prefers a woman for bathing. Call before arriving so she can sit up and put her wrap on.",
  },
  importantInfo: {
    bloodType: "O+",
    primaryPhysician: "Dr. Priya Patel",
    physicianPhone: "(410) 555-0198",
    pharmacy: "CVS Pharmacy, York Road",
    insuranceProvider: "Medicare",
    insuranceId: "1EG4-TE5-MK72",
    hospitalPreference: "Greater Baltimore Medical Center",
    medicalNotes: "Check blood pressure in the evening. She can feel dizzy if she stands too quickly.",
    other: "Advance directive is with Sarah. Front door code is shared in the circle notes.",
  },
  care: {
    status: CARE_STATUS.STABLE,
    summary: "Morning medication taken. Blood pressure is in range. Maya is covering the afternoon walk.",
    updatedAt: "2026-09-01T12:48:00.000Z",
    coverageNote: "Maya Chen on duty today · Dr. Patel next visit Wednesday",
  },
});

export const mockCircle = [
  createCareCircleMember({
    id: "m1",
    seniorId: "senior-eleanor",
    userId: "user-family",
    name: "Sarah Walsh",
    email: "family@famielda.test",
    role: CARE_CIRCLE_ROLES.OWNER,
    relationship: "Daughter",
    status: CIRCLE_STATUS.ACTIVE,
    kind: CIRCLE_KINDS.FAMILY,
    permissions: permissionsForRole(CARE_CIRCLE_ROLES.OWNER),
    availability: AVAILABILITY.AVAILABLE,
    lastSeenAt: "2026-09-01T12:10:00.000Z",
    notes: "Coordinates the week and holds the household record.",
  }),
  createCareCircleMember({
    id: "m2",
    seniorId: "senior-eleanor",
    name: "James Walsh",
    email: "chidi@famielda.test",
    role: CARE_CIRCLE_ROLES.COORDINATOR,
    relationship: "Son",
    status: CIRCLE_STATUS.ACTIVE,
    kind: CIRCLE_KINDS.FAMILY,
    permissions: permissionsForRole(CARE_CIRCLE_ROLES.COORDINATOR),
    availability: AVAILABILITY.AVAILABLE,
    lastSeenAt: "2026-08-31T21:40:00.000Z",
    nextVisit: "Wed · Cardiology ride",
    notes: "Driving Ellie to cardiology on Wednesday.",
  }),
  createCareCircleMember({
    id: "m3",
    seniorId: "senior-eleanor",
    userId: "user-caregiver",
    name: "Maya Chen",
    email: "caregiver@famielda.test",
    role: CARE_CIRCLE_ROLES.MEMBER,
    relationship: "Home caregiver",
    status: CIRCLE_STATUS.ACTIVE,
    kind: CIRCLE_KINDS.CAREGIVER,
    professionalType: PROFESSIONAL_TYPES.CNA,
    permissions: permissionsForRole(CARE_CIRCLE_ROLES.MEMBER),
    availability: AVAILABILITY.ON_DUTY,
    lastSeenAt: "2026-09-01T13:02:00.000Z",
    nextVisit: "Today · 3:30 p.m. walk",
    notes: "On duty today for personal care, the afternoon walk, and evening medication.",
  }),
  createCareCircleMember({
    id: "m4",
    seniorId: "senior-eleanor",
    name: "Nurse Rivera",
    email: "rivera@famielda.test",
    role: CARE_CIRCLE_ROLES.MEMBER,
    relationship: "Home health",
    status: CIRCLE_STATUS.ACTIVE,
    kind: CIRCLE_KINDS.PRACTITIONER,
    professionalType: PROFESSIONAL_TYPES.NURSE,
    permissions: permissionsForRole(CARE_CIRCLE_ROLES.MEMBER),
    availability: AVAILABILITY.AVAILABLE,
    lastSeenAt: "2026-08-31T16:20:00.000Z",
    nextVisit: "Fri · Home health check",
    notes: "Reviewed vitals yesterday. Next in-home check on Friday.",
  }),
  createCareCircleMember({
    id: "m5",
    seniorId: "senior-eleanor",
    userId: "user-practitioner",
    name: "Dr. Priya Patel",
    email: "practitioner@famielda.test",
    role: CARE_CIRCLE_ROLES.MEMBER,
    relationship: "Primary physician",
    status: CIRCLE_STATUS.ACTIVE,
    kind: CIRCLE_KINDS.PRACTITIONER,
    professionalType: PROFESSIONAL_TYPES.MD,
    permissions: permissionsForRole(CARE_CIRCLE_ROLES.MEMBER),
    availability: AVAILABILITY.AVAILABLE,
    lastSeenAt: "2026-08-25T15:00:00.000Z",
    nextVisit: "Wed · Cardiology follow-up",
    notes: "Following blood pressure and the Wednesday cardiology visit.",
  }),
  createCareCircleMember({
    id: "m7",
    seniorId: "senior-eleanor",
    name: "Sam Okeke",
    email: "physio@famielda.test",
    role: CARE_CIRCLE_ROLES.MEMBER,
    relationship: "Physiotherapist",
    status: CIRCLE_STATUS.ACTIVE,
    kind: CIRCLE_KINDS.PRACTITIONER,
    professionalType: PROFESSIONAL_TYPES.PHYSIOTHERAPIST,
    permissions: permissionsForRole(CARE_CIRCLE_ROLES.MEMBER),
    availability: AVAILABILITY.AVAILABLE,
    lastSeenAt: "2026-08-29T10:15:00.000Z",
    nextVisit: "Thu · Mobility session",
    notes: "Garden-path walks and chair strength twice a week.",
  }),
  createCareCircleMember({
    id: "m6",
    seniorId: "senior-eleanor",
    userId: "user-kemi",
    name: "Kate Walsh",
    email: "kemi@famielda.test",
    role: CARE_CIRCLE_ROLES.MEMBER,
    relationship: "Niece",
    status: CIRCLE_STATUS.INVITED,
    kind: CIRCLE_KINDS.FAMILY,
    permissions: permissionsForRole(CARE_CIRCLE_ROLES.MEMBER),
    invitedBy: "user-family",
    invitedAt: "2026-09-01T08:20:00.000Z",
    notes: "Waiting to join Ellie’s circle.",
  }),
];

export const mockInvites = [
  createCareCircleInvite({
    id: "inv-kemi",
    token: "invite-kemi-eleanor",
    seniorId: "senior-eleanor",
    seniorName: "Eleanor Walsh",
    email: "kemi@famielda.test",
    name: "Kate Walsh",
    kind: CIRCLE_KINDS.FAMILY,
    role: CARE_CIRCLE_ROLES.MEMBER,
    relationship: "Niece",
    permissions: permissionsForRole(CARE_CIRCLE_ROLES.MEMBER),
    status: INVITE_STATUS.PENDING,
    invitedBy: "user-family",
    invitedByName: "Sarah Walsh",
    memberId: "m6",
    message: "Ellie would like you in the circle for rides and Sunday lunch.",
    createdAt: "2026-09-01T08:20:00.000Z",
    updatedAt: "2026-09-01T08:20:00.000Z",
  }),
  createCareCircleInvite({
    id: "inv-maya-joseph",
    token: "invite-maya-joseph",
    seniorId: "senior-joseph",
    seniorName: "Joseph Brooks",
    email: "caregiver@famielda.test",
    name: "Maya Chen",
    kind: CIRCLE_KINDS.CAREGIVER,
    role: CARE_CIRCLE_ROLES.MEMBER,
    relationship: "Home caregiver",
    professionalType: PROFESSIONAL_TYPES.CNA,
    permissions: permissionsForRole(CARE_CIRCLE_ROLES.MEMBER),
    status: INVITE_STATUS.PENDING,
    invitedBy: "user-abena",
    invitedByName: "Lauren Brooks",
    memberId: null,
    message: "Joseph needs afternoon coverage three days a week. Can you join his circle?",
    createdAt: "2026-09-01T19:10:00.000Z",
    updatedAt: "2026-09-01T19:10:00.000Z",
  }),
  createCareCircleInvite({
    id: "inv-patel-joseph",
    token: "invite-patel-joseph",
    seniorId: "senior-joseph",
    seniorName: "Joseph Brooks",
    email: "practitioner@famielda.test",
    name: "Dr. Priya Patel",
    kind: CIRCLE_KINDS.PRACTITIONER,
    role: CARE_CIRCLE_ROLES.MEMBER,
    relationship: "Consulting physician",
    professionalType: PROFESSIONAL_TYPES.MD,
    permissions: permissionsForRole(CARE_CIRCLE_ROLES.MEMBER),
    status: INVITE_STATUS.PENDING,
    invitedBy: "user-abena",
    invitedByName: "Lauren Brooks",
    memberId: null,
    message: "Joseph’s family would like you to review his blood pressure plan.",
    createdAt: "2026-09-01T19:30:00.000Z",
    updatedAt: "2026-09-01T19:30:00.000Z",
  }),
];

export const mockEvents = [
  createScheduleEvent({ id: "e1", title: "Morning medication", weekday: 1, time: "08:00", type: "meds", assignee: "Sarah" }),
  createScheduleEvent({ id: "e4", title: "Pharmacy pickup", weekday: 4, time: "16:00", type: "errand", assignee: "Sarah" }),
  createScheduleEvent({ id: "e5", title: "Sunday lunch", weekday: 0, time: "13:00", type: "family", assignee: "Circle" }),
  createScheduleEvent({ id: "e6", title: "Morning medication", weekday: 2, time: "08:00", type: "meds", assignee: "Sarah" }),
];

function mayaVisit(data) {
  return createScheduleVisit({
    professionalKind: PROFESSIONAL_KIND.CAREGIVER,
    caregiverUserId: "user-caregiver",
    caregiverEmail: "caregiver@famielda.test",
    caregiverName: "Maya Chen",
    caregiverMemberId: data.caregiverMemberId ?? "m3",
    timeZone: data.timeZone ?? "America/New_York",
    ...data,
  });
}

function patelVisit(data) {
  return createScheduleVisit({
    professionalKind: PROFESSIONAL_KIND.PRACTITIONER,
    caregiverUserId: "user-practitioner",
    caregiverEmail: "practitioner@famielda.test",
    caregiverName: "Dr. Priya Patel",
    caregiverMemberId: data.caregiverMemberId ?? "m5",
    timeZone: data.timeZone ?? "America/New_York",
    ...data,
  });
}

export const mockAvailability = [
  createAvailabilityWindow({
    id: "av-maya-1",
    caregiverUserId: "user-caregiver",
    caregiverEmail: "caregiver@famielda.test",
    caregiverName: "Maya Chen",
    kind: AVAILABILITY_KIND.WEEKLY,
    weekday: 1,
    startTime: "08:00",
    endTime: "18:00",
  }),
  createAvailabilityWindow({
    id: "av-maya-2",
    caregiverUserId: "user-caregiver",
    caregiverEmail: "caregiver@famielda.test",
    caregiverName: "Maya Chen",
    kind: AVAILABILITY_KIND.WEEKLY,
    weekday: 2,
    startTime: "08:00",
    endTime: "18:00",
  }),
  createAvailabilityWindow({
    id: "av-maya-3",
    caregiverUserId: "user-caregiver",
    caregiverEmail: "caregiver@famielda.test",
    caregiverName: "Maya Chen",
    kind: AVAILABILITY_KIND.WEEKLY,
    weekday: 3,
    startTime: "08:00",
    endTime: "18:00",
  }),
  createAvailabilityWindow({
    id: "av-maya-4",
    caregiverUserId: "user-caregiver",
    caregiverEmail: "caregiver@famielda.test",
    caregiverName: "Maya Chen",
    kind: AVAILABILITY_KIND.WEEKLY,
    weekday: 4,
    startTime: "08:00",
    endTime: "18:00",
  }),
  createAvailabilityWindow({
    id: "av-maya-5",
    caregiverUserId: "user-caregiver",
    caregiverEmail: "caregiver@famielda.test",
    caregiverName: "Maya Chen",
    kind: AVAILABILITY_KIND.WEEKLY,
    weekday: 5,
    startTime: "08:00",
    endTime: "18:00",
  }),
  createAvailabilityWindow({
    id: "av-maya-6",
    caregiverUserId: "user-caregiver",
    caregiverEmail: "caregiver@famielda.test",
    caregiverName: "Maya Chen",
    kind: AVAILABILITY_KIND.WEEKLY,
    weekday: 6,
    startTime: "10:00",
    endTime: "14:00",
  }),
  createAvailabilityWindow({
    id: "av-patel-1",
    professionalKind: PROFESSIONAL_KIND.PRACTITIONER,
    caregiverUserId: "user-practitioner",
    caregiverEmail: "practitioner@famielda.test",
    caregiverName: "Dr. Priya Patel",
    kind: AVAILABILITY_KIND.WEEKLY,
    weekday: 1,
    startTime: "09:00",
    endTime: "12:00",
  }),
  createAvailabilityWindow({
    id: "av-patel-3",
    professionalKind: PROFESSIONAL_KIND.PRACTITIONER,
    caregiverUserId: "user-practitioner",
    caregiverEmail: "practitioner@famielda.test",
    caregiverName: "Dr. Priya Patel",
    kind: AVAILABILITY_KIND.WEEKLY,
    weekday: 3,
    startTime: "09:00",
    endTime: "16:00",
  }),
  createAvailabilityWindow({
    id: "av-patel-5",
    professionalKind: PROFESSIONAL_KIND.PRACTITIONER,
    caregiverUserId: "user-practitioner",
    caregiverEmail: "practitioner@famielda.test",
    caregiverName: "Dr. Priya Patel",
    kind: AVAILABILITY_KIND.WEEKLY,
    weekday: 5,
    startTime: "09:00",
    endTime: "12:00",
  }),
];

export const mockVisits = [
  mayaVisit({
    id: "visit-mon-breakfast",
    seniorId: "senior-eleanor",
    seniorName: "Eleanor Walsh",
    familyId: "user-family",
    familyName: "Sarah Walsh",
    title: "Morning stretch and breakfast",
    date: dateForWeekday(1),
    startTime: "08:30",
    endTime: "11:00",
    originalEndTime: "11:00",
    status: VISIT_STATUS.CHECKED_OUT,
    requestedBy: "user-family",
    requestedByName: "Sarah Walsh",
    requestedAt: "2026-08-29T18:10:00.000Z",
    respondedAt: "2026-08-29T18:40:00.000Z",
    checkedInAt: stampAt(1, 8, 32),
    checkedOutAt: stampAt(1, 10, 55),
    notes: [
      createVisitNote({
        id: "note-mon-1",
        body: "Ellie ate most of breakfast. Short stretch at the kitchen chair before tea.",
        author: "Maya Chen",
        authorId: "user-caregiver",
        createdAt: stampAt(1, 10, 40),
      }),
    ],
    report: createVisitReport({
      summary: "Morning stretch and breakfast covered. Appetite was good. No dizziness after standing.",
      mood: "typical",
      meals: "Oatmeal, banana, and tea.",
      mobility: "Chair stretches. Walker to the table.",
      concerns: "None new.",
      followUp: "Keep the evening BP log going into Tuesday’s check.",
      submittedAt: stampAt(1, 11, 5),
      submittedBy: "Maya Chen",
      submittedById: "user-caregiver",
    }),
    createdAt: "2026-08-29T18:10:00.000Z",
    updatedAt: stampAt(1, 11, 5),
  }),
  mayaVisit({
    id: "visit-tue-bp",
    seniorId: "senior-eleanor",
    seniorName: "Eleanor Walsh",
    familyId: "user-family",
    familyName: "Sarah Walsh",
    title: "Blood pressure check",
    date: dateForWeekday(2),
    startTime: "09:30",
    endTime: "11:00",
    originalEndTime: "11:00",
    status: VISIT_STATUS.CHECKED_OUT,
    requestedBy: "user-family",
    requestedByName: "Sarah Walsh",
    requestedAt: "2026-08-30T14:10:00.000Z",
    respondedAt: "2026-08-30T15:02:00.000Z",
    checkedInAt: "2026-09-01T09:28:00.000Z",
    checkedOutAt: "2026-09-01T10:48:00.000Z",
    notes: [
      createVisitNote({
        id: "note-tue-1",
        body: "BP 128/76. Ellie was steady with the walker after the check.",
        author: "Maya Chen",
        authorId: "user-caregiver",
        createdAt: "2026-09-01T10:40:00.000Z",
      }),
    ],
    report: createVisitReport({
      summary: "Morning check completed. Blood pressure in range. Short loop around the block after.",
      mood: "good",
      meals: "Tea and toast before the visit.",
      mobility: "Walker. Steady on the block loop.",
      concerns: "None new.",
      followUp: "Keep the evening BP log going into Wednesday’s cardiology visit.",
      submittedAt: "2026-09-01T10:50:00.000Z",
      submittedBy: "Maya Chen",
      submittedById: "user-caregiver",
    }),
    createdAt: "2026-08-30T14:10:00.000Z",
    updatedAt: "2026-09-01T10:50:00.000Z",
  }),
  mayaVisit({
    id: "visit-wed-morning",
    seniorId: "senior-eleanor",
    seniorName: "Eleanor Walsh",
    familyId: "user-family",
    familyName: "Sarah Walsh",
    title: "Morning personal care",
    date: dateForWeekday(3),
    startTime: "08:30",
    endTime: "12:15",
    originalEndTime: "11:00",
    status: VISIT_STATUS.CHECKED_OUT,
    requestedBy: "user-family",
    requestedByName: "Sarah Walsh",
    requestedAt: "2026-08-31T09:12:00.000Z",
    respondedAt: "2026-08-31T09:40:00.000Z",
    checkedInAt: stampAt(3, 9, 5),
    checkedOutAt: stampAt(3, 12, 5),
    notes: [],
    createdAt: "2026-08-31T09:12:00.000Z",
    updatedAt: stampAt(3, 12, 5),
  }),
  mayaVisit({
    id: "visit-wed-walk",
    seniorId: "senior-eleanor",
    seniorName: "Eleanor Walsh",
    familyId: "user-family",
    familyName: "Sarah Walsh",
    title: "Afternoon walk",
    date: dateForWeekday(3),
    startTime: "15:30",
    endTime: "17:00",
    originalEndTime: "17:00",
    status: VISIT_STATUS.ACCEPTED,
    requestedBy: "user-family",
    requestedByName: "Sarah Walsh",
    requestedAt: "2026-08-31T09:12:00.000Z",
    respondedAt: "2026-08-31T09:40:00.000Z",
    notes: [
      createVisitNote({
        id: "note-walk-1",
        body: "Garden path if it is not too warm. Bring water.",
        author: "Sarah Walsh",
        authorId: "user-family",
        createdAt: "2026-09-01T09:12:00.000Z",
      }),
    ],
    createdAt: "2026-08-31T09:12:00.000Z",
    updatedAt: "2026-08-31T09:40:00.000Z",
  }),
  mayaVisit({
    id: "visit-thu-lunch",
    seniorId: "senior-eleanor",
    seniorName: "Eleanor Walsh",
    familyId: "user-family",
    familyName: "Sarah Walsh",
    title: "Companionship and lunch",
    date: dateForWeekday(4),
    startTime: "12:00",
    endTime: "16:00",
    originalEndTime: "16:00",
    status: VISIT_STATUS.ACCEPTED,
    requestedBy: "user-family",
    requestedByName: "Sarah Walsh",
    requestedAt: "2026-08-31T11:20:00.000Z",
    respondedAt: "2026-08-31T11:44:00.000Z",
    createdAt: "2026-08-31T11:20:00.000Z",
    updatedAt: "2026-08-31T11:44:00.000Z",
  }),
  mayaVisit({
    id: "visit-fri-request",
    seniorId: "senior-eleanor",
    seniorName: "Eleanor Walsh",
    familyId: "user-family",
    familyName: "Sarah Walsh",
    title: "Companion visit",
    date: dateForWeekday(5),
    startTime: "10:00",
    endTime: "14:00",
    originalEndTime: "14:00",
    status: VISIT_STATUS.REQUESTED,
    requestedBy: "user-family",
    requestedByName: "Sarah Walsh",
    requestedAt: "2026-09-01T16:05:00.000Z",
    createdAt: "2026-09-01T16:05:00.000Z",
    updatedAt: "2026-09-01T16:05:00.000Z",
  }),
  mayaVisit({
    id: "visit-sat-companion",
    seniorId: "senior-eleanor",
    seniorName: "Eleanor Walsh",
    familyId: "user-family",
    familyName: "Sarah Walsh",
    title: "Companion visit",
    date: dateForWeekday(6),
    startTime: "11:00",
    endTime: "13:00",
    originalEndTime: "13:00",
    status: VISIT_STATUS.ACCEPTED,
    requestedBy: "user-family",
    requestedByName: "Sarah Walsh",
    requestedAt: "2026-08-31T18:10:00.000Z",
    respondedAt: "2026-08-31T18:22:00.000Z",
    createdAt: "2026-08-31T18:10:00.000Z",
    updatedAt: "2026-08-31T18:22:00.000Z",
  }),
  mayaVisit({
    id: "visit-joseph-overlap",
    seniorId: "senior-joseph",
    seniorName: "Joseph Brooks",
    familyId: "user-abena",
    familyName: "Lauren Brooks",
    caregiverMemberId: "",
    title: "Afternoon coverage",
    date: dateForWeekday(3),
    startTime: "15:00",
    endTime: "18:00",
    originalEndTime: "18:00",
    status: VISIT_STATUS.REQUESTED,
    requestedBy: "user-abena",
    requestedByName: "Lauren Brooks",
    requestedAt: "2026-09-01T19:20:00.000Z",
    createdAt: "2026-09-01T19:20:00.000Z",
    updatedAt: "2026-09-01T19:20:00.000Z",
  }),
  patelVisit({
    id: "appt-wed-bp",
    seniorId: "senior-eleanor",
    seniorName: "Eleanor Walsh",
    familyId: "user-family",
    familyName: "Sarah Walsh",
    title: "Pre-visit BP review",
    date: dateForWeekday(3),
    startTime: "10:00",
    endTime: "10:45",
    originalEndTime: "10:45",
    status: VISIT_STATUS.ACCEPTED,
    requestedBy: "user-family",
    requestedByName: "Sarah Walsh",
    requestedAt: "2026-08-30T16:40:00.000Z",
    respondedAt: "2026-08-30T17:05:00.000Z",
    notes: [
      createVisitNote({
        id: "note-bp-review",
        body: "Review the evening BP log before GBMC.",
        author: "Sarah Walsh",
        authorId: "user-family",
        createdAt: "2026-08-30T16:42:00.000Z",
      }),
    ],
    createdAt: "2026-08-30T16:40:00.000Z",
    updatedAt: "2026-08-30T17:05:00.000Z",
  }),
  patelVisit({
    id: "appt-fri-consult",
    seniorId: "senior-eleanor",
    seniorName: "Eleanor Walsh",
    familyId: "user-family",
    familyName: "Sarah Walsh",
    title: "Medication review",
    date: dateForWeekday(5),
    startTime: "09:00",
    endTime: "09:45",
    originalEndTime: "09:45",
    status: VISIT_STATUS.REQUESTED,
    requestedBy: "user-family",
    requestedByName: "Sarah Walsh",
    requestedAt: "2026-09-01T16:20:00.000Z",
    createdAt: "2026-09-01T16:20:00.000Z",
    updatedAt: "2026-09-01T16:20:00.000Z",
  }),
  patelVisit({
    id: "appt-joseph-overlap",
    seniorId: "senior-joseph",
    seniorName: "Joseph Brooks",
    familyId: "user-abena",
    familyName: "Lauren Brooks",
    caregiverMemberId: "",
    title: "BP plan review",
    date: dateForWeekday(3),
    startTime: "10:15",
    endTime: "11:00",
    originalEndTime: "11:00",
    status: VISIT_STATUS.REQUESTED,
    requestedBy: "user-abena",
    requestedByName: "Lauren Brooks",
    requestedAt: "2026-09-01T19:35:00.000Z",
    createdAt: "2026-09-01T19:35:00.000Z",
    updatedAt: "2026-09-01T19:35:00.000Z",
  }),
];

export const mockCarePlans = [
  createCarePlan({
    id: "plan-ellie-daily",
    seniorId: "senior-eleanor",
    title: "Daily support plan",
    goal: "Keep Ellie’s mornings unhurried, blood pressure in range, and a short walk in the afternoon.",
    notes: "Prefers a woman for bathing. Call before arriving so she can sit up and put her wrap on.",
    status: CARE_PLAN_STATUS.ACTIVE,
    startDate: dateForWeekday(1),
    createdBy: "user-family",
    createdByName: "Sarah Walsh",
    updatedBy: "user-family",
    updatedByName: "Sarah Walsh",
    createdAt: "2026-08-28T14:20:00.000Z",
    updatedAt: "2026-09-01T09:10:00.000Z",
  }),
];

export const mockCarePlanTasks = [
  createCarePlanTask({
    id: "task-ellie-meds-am",
    planId: "plan-ellie-daily",
    seniorId: "senior-eleanor",
    title: "Morning medication",
    notes: "Lisinopril 10mg with tea. Do not rush her.",
    category: CARE_TASK_CATEGORY.MEDICATION,
    priority: CARE_TASK_PRIORITY.HIGH,
    frequency: CARE_TASK_FREQUENCY.DAILY,
    dueDate: dateForWeekday(3),
    dueTime: "08:00",
    assignedCaregiverId: "m3",
    assignedCaregiverUserId: "user-caregiver",
    assignedCaregiverEmail: "caregiver@famielda.test",
    assignedCaregiverName: "Maya Chen",
    status: CARE_TASK_STATUS.OPEN,
    lastCompletedAt: stampAt(3, 10, 30),
    lastCompletedBy: "user-caregiver",
    lastCompletedByName: "Maya Chen",
    completionCount: 5,
    createdBy: "user-family",
    createdByName: "Sarah Walsh",
    createdAt: "2026-08-28T14:22:00.000Z",
    updatedAt: stampAt(3, 10, 30),
  }),
  createCarePlanTask({
    id: "task-ellie-lunch",
    planId: "plan-ellie-daily",
    seniorId: "senior-eleanor",
    title: "Low-sodium lunch",
    notes: "Follow the recorded diet. She likes pepper soup on Sundays.",
    category: CARE_TASK_CATEGORY.NUTRITION,
    priority: CARE_TASK_PRIORITY.MEDIUM,
    frequency: CARE_TASK_FREQUENCY.DAILY,
    dueDate: dateForWeekday(4),
    dueTime: "12:00",
    assignedCaregiverId: "m3",
    assignedCaregiverUserId: "user-caregiver",
    assignedCaregiverEmail: "caregiver@famielda.test",
    assignedCaregiverName: "Maya Chen",
    status: CARE_TASK_STATUS.OPEN,
    lastCompletedAt: stampAt(3, 12, 20),
    lastCompletedBy: "user-caregiver",
    lastCompletedByName: "Maya Chen",
    completionCount: 5,
    createdBy: "user-family",
    createdByName: "Sarah Walsh",
    createdAt: "2026-08-28T14:24:00.000Z",
    updatedAt: stampAt(3, 12, 20),
  }),
  createCarePlanTask({
    id: "task-ellie-walk",
    planId: "plan-ellie-daily",
    seniorId: "senior-eleanor",
    title: "Afternoon walk",
    notes: "Garden path if it is not too warm. Keep it short if she is tired.",
    category: CARE_TASK_CATEGORY.MOBILITY,
    priority: CARE_TASK_PRIORITY.LOW,
    frequency: CARE_TASK_FREQUENCY.DAILY,
    dueDate: dateForWeekday(3),
    dueTime: "15:30",
    assignedCaregiverId: "m3",
    assignedCaregiverUserId: "user-caregiver",
    assignedCaregiverEmail: "caregiver@famielda.test",
    assignedCaregiverName: "Maya Chen",
    status: CARE_TASK_STATUS.OPEN,
    lastCompletedAt: "2026-09-01T16:02:00.000Z",
    lastCompletedBy: "user-caregiver",
    lastCompletedByName: "Maya Chen",
    completionCount: 3,
    createdBy: "user-family",
    createdByName: "Sarah Walsh",
    createdAt: "2026-08-28T14:26:00.000Z",
    updatedAt: "2026-09-01T16:02:00.000Z",
  }),
  createCarePlanTask({
    id: "task-ellie-bp",
    planId: "plan-ellie-daily",
    seniorId: "senior-eleanor",
    title: "Evening blood pressure",
    notes: "Check in the evening. She can feel dizzy if she stands too quickly.",
    category: CARE_TASK_CATEGORY.CLINICAL,
    priority: CARE_TASK_PRIORITY.HIGH,
    frequency: CARE_TASK_FREQUENCY.DAILY,
    dueDate: dateForWeekday(3),
    dueTime: "19:00",
    assignedCaregiverId: "m3",
    assignedCaregiverUserId: "user-caregiver",
    assignedCaregiverEmail: "caregiver@famielda.test",
    assignedCaregiverName: "Maya Chen",
    status: CARE_TASK_STATUS.OPEN,
    lastCompletedAt: "2026-09-01T19:18:00.000Z",
    lastCompletedBy: "user-caregiver",
    lastCompletedByName: "Maya Chen",
    completionCount: 4,
    createdBy: "user-practitioner",
    createdByName: "Dr. Priya Patel",
    createdAt: "2026-08-28T15:10:00.000Z",
    updatedAt: "2026-09-01T19:18:00.000Z",
  }),
  createCarePlanTask({
    id: "task-ellie-cardio-prep",
    planId: "plan-ellie-daily",
    seniorId: "senior-eleanor",
    title: "Cardiology visit prep",
    notes: "Bring the evening BP log. James is driving to GBMC.",
    category: CARE_TASK_CATEGORY.CLINICAL,
    priority: CARE_TASK_PRIORITY.URGENT,
    frequency: CARE_TASK_FREQUENCY.ONCE,
    dueDate: dateForWeekday(3),
    dueTime: "13:30",
    assignedCaregiverId: "m2",
    assignedCaregiverUserId: "",
    assignedCaregiverEmail: "chidi@famielda.test",
    assignedCaregiverName: "James Walsh",
    status: CARE_TASK_STATUS.OPEN,
    completionCount: 0,
    createdBy: "user-family",
    createdByName: "Sarah Walsh",
    createdAt: "2026-08-31T11:20:00.000Z",
    updatedAt: "2026-08-31T11:20:00.000Z",
  }),
  createCarePlanTask({
    id: "task-ellie-home-health",
    planId: "plan-ellie-daily",
    seniorId: "senior-eleanor",
    title: "Home health check notes",
    notes: "Review vitals and send a short note to the circle.",
    category: CARE_TASK_CATEGORY.CLINICAL,
    priority: CARE_TASK_PRIORITY.MEDIUM,
    frequency: CARE_TASK_FREQUENCY.WEEKLY,
    dueDate: dateForWeekday(5),
    dueTime: "10:00",
    weekday: 5,
    assignedCaregiverId: "m4",
    assignedCaregiverUserId: "",
    assignedCaregiverEmail: "rivera@famielda.test",
    assignedCaregiverName: "Nurse Rivera",
    status: CARE_TASK_STATUS.OPEN,
    lastCompletedAt: "2026-08-29T10:40:00.000Z",
    lastCompletedBy: "",
    lastCompletedByName: "Nurse Rivera",
    completionCount: 1,
    createdBy: "user-practitioner",
    createdByName: "Dr. Priya Patel",
    createdAt: "2026-08-28T15:18:00.000Z",
    updatedAt: "2026-08-29T10:40:00.000Z",
  }),
  createCarePlanTask({
    id: "task-ellie-refill",
    planId: "plan-ellie-daily",
    seniorId: "senior-eleanor",
    title: "Refill lisinopril",
    notes: "CVS on North Avenue. Ask for the 90-day fill if the insurance allows it.",
    category: CARE_TASK_CATEGORY.MEDICATION,
    priority: CARE_TASK_PRIORITY.HIGH,
    frequency: CARE_TASK_FREQUENCY.ONCE,
    dueDate: dateForWeekday(1),
    dueTime: "16:00",
    assignedCaregiverId: "m2",
    assignedCaregiverUserId: "",
    assignedCaregiverEmail: "chidi@famielda.test",
    assignedCaregiverName: "James Walsh",
    status: CARE_TASK_STATUS.OPEN,
    completionCount: 0,
    notesLog: [
      {
        id: "note-ellie-refill-1",
        body: "Pharmacy said Wednesday is the earliest the 90-day fill can be ready.",
        createdAt: "2026-08-31T18:40:00.000Z",
        createdBy: "user-family",
        createdByName: "Sarah Walsh",
      },
    ],
    createdBy: "user-family",
    createdByName: "Sarah Walsh",
    createdAt: "2026-08-30T12:10:00.000Z",
    updatedAt: "2026-08-31T18:40:00.000Z",
  }),
  createCarePlanTask({
    id: "task-ellie-med-review",
    planId: "plan-ellie-daily",
    seniorId: "senior-eleanor",
    title: "Monthly medication review",
    notes: "Confirm doses with Dr. Patel and note any dizziness from the evening BP checks.",
    category: CARE_TASK_CATEGORY.CLINICAL,
    priority: CARE_TASK_PRIORITY.MEDIUM,
    frequency: CARE_TASK_FREQUENCY.MONTHLY,
    dueDate: dateForWeekday(5),
    dueTime: "11:00",
    assignedCaregiverId: "m5",
    assignedCaregiverUserId: "user-practitioner",
    assignedCaregiverEmail: "practitioner@famielda.test",
    assignedCaregiverName: "Dr. Priya Patel",
    status: CARE_TASK_STATUS.OPEN,
    completionCount: 0,
    createdBy: "user-family",
    createdByName: "Sarah Walsh",
    createdAt: "2026-08-28T15:22:00.000Z",
    updatedAt: "2026-08-28T15:22:00.000Z",
  }),
];

export const mockCarePlanCompletions = [
  createCarePlanCompletion({
    id: "done-ellie-meds-tue",
    taskId: "task-ellie-meds-am",
    planId: "plan-ellie-daily",
    seniorId: "senior-eleanor",
    outcome: CARE_TASK_STATUS.COMPLETED,
    notes: "Taken with tea. No rush.",
    dueDate: dateForWeekday(2),
    completedAt: "2026-09-01T08:12:00.000Z",
    completedBy: "user-caregiver",
    completedByName: "Maya Chen",
  }),
  createCarePlanCompletion({
    id: "done-ellie-walk-tue",
    taskId: "task-ellie-walk",
    planId: "plan-ellie-daily",
    seniorId: "senior-eleanor",
    outcome: CARE_TASK_STATUS.COMPLETED,
    notes: "Short garden loop. Water taken.",
    dueDate: dateForWeekday(2),
    completedAt: "2026-09-01T16:02:00.000Z",
    completedBy: "user-caregiver",
    completedByName: "Maya Chen",
  }),
  createCarePlanCompletion({
    id: "done-ellie-bp-tue",
    taskId: "task-ellie-bp",
    planId: "plan-ellie-daily",
    seniorId: "senior-eleanor",
    outcome: CARE_TASK_STATUS.COMPLETED,
    notes: "128/76. In range.",
    dueDate: dateForWeekday(2),
    completedAt: "2026-09-01T19:18:00.000Z",
    completedBy: "user-caregiver",
    completedByName: "Maya Chen",
  }),
  createCarePlanCompletion({
    id: "done-ellie-lunch-wed",
    taskId: "task-ellie-lunch",
    planId: "plan-ellie-daily",
    seniorId: "senior-eleanor",
    outcome: CARE_TASK_STATUS.COMPLETED,
    notes: "Full meal and water.",
    dueDate: dateForWeekday(3),
    completedAt: stampAt(3, 12, 20),
    completedBy: "user-caregiver",
    completedByName: "Maya Chen",
  }),
  createCarePlanCompletion({
    id: "done-ellie-meds-wed",
    taskId: "task-ellie-meds-am",
    planId: "plan-ellie-daily",
    seniorId: "senior-eleanor",
    outcome: CARE_TASK_STATUS.COMPLETED,
    notes: "Taken with tea. No rush.",
    dueDate: dateForWeekday(3),
    completedAt: stampAt(3, 10, 30),
    completedBy: "user-caregiver",
    completedByName: "Maya Chen",
  }),
];

function mockAppointment(data) {
  return createAppointment({
    reminderAt: appointmentReminderAt(data.date, data.time, data.reminder),
    createdBy: "user-family",
    createdByName: "Sarah Walsh",
    updatedBy: "user-family",
    updatedByName: "Sarah Walsh",
    ...data,
  });
}

export const mockAppointments = [
  mockAppointment({
    id: "appt-ellie-cardiology",
    seniorId: "senior-eleanor",
    title: "Cardiology follow-up",
    date: dateForWeekday(3),
    time: "14:15",
    endTime: "15:00",
    location: "GBMC",
    notes: "James is driving. Bring the latest blood pressure log.",
    status: APPOINTMENT_STATUS.CONFIRMED,
    practitionerId: "m5",
    practitionerUserId: "user-practitioner",
    practitionerEmail: "practitioner@famielda.test",
    practitionerName: "Dr. Priya Patel",
    reminder: APPOINTMENT_REMINDER.DAY_1,
    reminderSent: true,
    createdAt: "2026-08-25T15:10:00.000Z",
    updatedAt: "2026-09-01T11:10:00.000Z",
  }),
  mockAppointment({
    id: "appt-ellie-home-health",
    seniorId: "senior-eleanor",
    title: "Home health check",
    date: dateForWeekday(5),
    time: "10:00",
    endTime: "10:45",
    location: "Home",
    notes: "Vitals and a short walk if she is steady.",
    status: APPOINTMENT_STATUS.SCHEDULED,
    practitionerId: "m4",
    practitionerUserId: "",
    practitionerEmail: "rivera@famielda.test",
    practitionerName: "Nurse Rivera",
    reminder: APPOINTMENT_REMINDER.HOUR_1,
    reminderSent: false,
    createdAt: "2026-08-28T16:40:00.000Z",
    updatedAt: "2026-08-28T16:40:00.000Z",
  }),
  mockAppointment({
    id: "appt-ellie-labs",
    seniorId: "senior-eleanor",
    title: "Lab work",
    date: "2026-09-18",
    time: "09:00",
    endTime: "09:30",
    location: "Bayview lab",
    notes: "Fasting bloodwork. Water only after midnight.",
    status: APPOINTMENT_STATUS.SCHEDULED,
    practitionerId: "m5",
    practitionerUserId: "user-practitioner",
    practitionerEmail: "practitioner@famielda.test",
    practitionerName: "Dr. Priya Patel",
    reminder: APPOINTMENT_REMINDER.DAY_2,
    reminderSent: false,
    createdAt: "2026-09-01T09:20:00.000Z",
    updatedAt: "2026-09-01T09:20:00.000Z",
  }),
  mockAppointment({
    id: "appt-ellie-physio",
    seniorId: "senior-eleanor",
    title: "Physiotherapy",
    date: "2026-08-28",
    time: "11:00",
    endTime: "11:45",
    location: "Harbor Rehab",
    notes: "Knee mobility. She did the full set.",
    status: APPOINTMENT_STATUS.COMPLETED,
    practitionerId: "",
    practitionerName: "",
    reminder: APPOINTMENT_REMINDER.NONE,
    reminderSent: true,
    createdAt: "2026-08-20T13:00:00.000Z",
    updatedAt: "2026-08-28T12:05:00.000Z",
  }),
  mockAppointment({
    id: "appt-ellie-optometry",
    seniorId: "senior-eleanor",
    title: "Optometry",
    date: "2026-09-10",
    time: "13:30",
    endTime: "14:15",
    location: "Charles Street Eye",
    notes: "Reschedule after the cardiology visit.",
    status: APPOINTMENT_STATUS.CANCELLED,
    practitionerId: "",
    reminder: APPOINTMENT_REMINDER.DAY_1,
    reminderSent: true,
    cancelledAt: "2026-09-01T16:12:00.000Z",
    cancelledBy: "user-family",
    cancelledByName: "Sarah Walsh",
    cancelReason: "Overlaps with rest after cardiology.",
    createdAt: "2026-08-22T10:00:00.000Z",
    updatedAt: "2026-09-01T16:12:00.000Z",
  }),
];

function mockMed(data) {
  return createMedication({
    reminderAt: medicationReminderAt(data),
    createdBy: "user-family",
    createdByName: "Sarah Walsh",
    updatedBy: "user-family",
    updatedByName: "Sarah Walsh",
    ...data,
  });
}

export const mockMedications = [
  mockMed({
    id: "med-ellie-lisinopril",
    seniorId: "senior-eleanor",
    name: "Lisinopril",
    dosage: "10mg",
    frequency: MEDICATION_FREQUENCY.DAILY,
    time: "08:00",
    startDate: "2024-03-12",
    endDate: "",
    reminder: MEDICATION_REMINDER.MINUTES_15,
    reminderSent: false,
    notes: "With morning tea and a full glass of water. This is what the household is covering — not a new order.",
    status: MEDICATION_STATUS.ACTIVE,
    responsibleId: "m1",
    responsibleUserId: "user-family",
    responsibleEmail: "family@famielda.test",
    responsibleName: "Sarah Walsh",
    clinicianId: "m5",
    clinicianUserId: "user-practitioner",
    clinicianEmail: "practitioner@famielda.test",
    clinicianName: "Dr. Priya Patel",
    createdAt: "2024-03-12T12:00:00.000Z",
    updatedAt: "2026-09-01T18:10:00.000Z",
  }),
  mockMed({
    id: "med-ellie-vitd",
    seniorId: "senior-eleanor",
    name: "Vitamin D",
    dosage: "2000 IU",
    frequency: MEDICATION_FREQUENCY.DAILY,
    time: "08:00",
    startDate: "2025-11-01",
    endDate: "",
    reminder: MEDICATION_REMINDER.AT_TIME,
    reminderSent: false,
    notes: "Same cup as the morning tea so it is not missed.",
    status: MEDICATION_STATUS.ACTIVE,
    responsibleId: "m3",
    responsibleUserId: "user-caregiver",
    responsibleEmail: "caregiver@famielda.test",
    responsibleName: "Maya Chen",
    clinicianId: "",
    createdAt: "2025-11-01T15:20:00.000Z",
    updatedAt: "2026-08-31T18:06:00.000Z",
  }),
  mockMed({
    id: "med-ellie-calcium",
    seniorId: "senior-eleanor",
    name: "Calcium carbonate",
    dosage: "500mg",
    frequency: MEDICATION_FREQUENCY.TWICE_DAILY,
    time: "08:00",
    secondTime: "20:00",
    startDate: "2026-06-01",
    endDate: "2026-08-15",
    reminder: MEDICATION_REMINDER.NONE,
    reminderSent: true,
    notes: "Evening dose with supper. Course ended; kept on the history.",
    status: MEDICATION_STATUS.ENDED,
    responsibleId: "m3",
    responsibleUserId: "user-caregiver",
    responsibleEmail: "caregiver@famielda.test",
    responsibleName: "Maya Chen",
    endedAt: "2026-08-15T21:00:00.000Z",
    endedBy: "user-family",
    endedByName: "Sarah Walsh",
    createdAt: "2026-06-01T10:00:00.000Z",
    updatedAt: "2026-08-15T21:00:00.000Z",
  }),
];

export const mockMedicationDoses = [
  createMedicationDose({
    id: "dose-lisinopril-mon",
    medicationId: "med-ellie-lisinopril",
    seniorId: "senior-eleanor",
    name: "Lisinopril",
    dosage: "10mg",
    date: dateForWeekday(1),
    time: "08:00",
    slotKey: `${dateForWeekday(1)}|08:00`,
    outcome: MEDICATION_DOSE_OUTCOME.TAKEN,
    notes: "Taken with tea. No rush.",
    recordedBy: "user-family",
    recordedByName: "Sarah Walsh",
    recordedAt: `${dateForWeekday(1)}T12:08:00.000Z`,
  }),
  createMedicationDose({
    id: "dose-vitd-mon",
    medicationId: "med-ellie-vitd",
    seniorId: "senior-eleanor",
    name: "Vitamin D",
    dosage: "2000 IU",
    date: dateForWeekday(1),
    time: "08:00",
    slotKey: `${dateForWeekday(1)}|08:00`,
    outcome: MEDICATION_DOSE_OUTCOME.TAKEN,
    notes: "",
    recordedBy: "user-family",
    recordedByName: "Sarah Walsh",
    recordedAt: `${dateForWeekday(1)}T12:10:00.000Z`,
  }),
  createMedicationDose({
    id: "dose-lisinopril-tue",
    medicationId: "med-ellie-lisinopril",
    seniorId: "senior-eleanor",
    name: "Lisinopril",
    dosage: "10mg",
    date: dateForWeekday(2),
    time: "08:00",
    slotKey: `${dateForWeekday(2)}|08:00`,
    outcome: MEDICATION_DOSE_OUTCOME.TAKEN,
    notes: "Morning medication taken. Blood pressure is in range.",
    recordedBy: "user-caregiver",
    recordedByName: "Maya Chen",
    recordedAt: `${dateForWeekday(2)}T12:14:00.000Z`,
  }),
  createMedicationDose({
    id: "dose-vitd-tue",
    medicationId: "med-ellie-vitd",
    seniorId: "senior-eleanor",
    name: "Vitamin D",
    dosage: "2000 IU",
    date: dateForWeekday(2),
    time: "08:00",
    slotKey: `${dateForWeekday(2)}|08:00`,
    outcome: MEDICATION_DOSE_OUTCOME.SKIPPED,
    notes: "Pharmacy bottle empty. Refill due Wednesday.",
    recordedBy: "user-caregiver",
    recordedByName: "Maya Chen",
    recordedAt: `${dateForWeekday(2)}T12:20:00.000Z`,
  }),
  createMedicationDose({
    id: "dose-lisinopril-wed",
    medicationId: "med-ellie-lisinopril",
    seniorId: "senior-eleanor",
    name: "Lisinopril",
    dosage: "10mg",
    date: dateForWeekday(3),
    time: "08:00",
    slotKey: `${dateForWeekday(3)}|08:00`,
    outcome: MEDICATION_DOSE_OUTCOME.TAKEN,
    notes: "Morning dose with tea.",
    recordedBy: "user-caregiver",
    recordedByName: "Maya Chen",
    recordedAt: stampAt(3, 11, 0),
  }),
  createMedicationDose({
    id: "dose-calcium-last",
    medicationId: "med-ellie-calcium",
    seniorId: "senior-eleanor",
    name: "Calcium carbonate",
    dosage: "500mg",
    date: "2026-08-15",
    time: "20:00",
    slotKey: "2026-08-15|20:00",
    outcome: MEDICATION_DOSE_OUTCOME.TAKEN,
    notes: "Last evening dose of the course.",
    recordedBy: "user-caregiver",
    recordedByName: "Maya Chen",
    recordedAt: "2026-08-15T20:12:00.000Z",
  }),
];

export const mockNotifications = [
  createNotification({
    id: "n-invite-family",
    type: NOTIFICATION_TYPES.FAMILY_INVITATION,
    title: "You’re invited to Ellie’s circle",
    body: "Sarah Walsh invited you to coordinate care with the household.",
    createdAt: "2026-09-02T08:10:00.000Z",
    read: false,
    inviteId: "inv-maya",
    inviteToken: "tok-family-demo",
  }),
  createNotification({
    id: "n-invite-caregiver",
    type: NOTIFICATION_TYPES.CAREGIVER_INVITATION,
    title: "Caregiver invitation",
    body: "Sarah asked Maya Chen to join Ellie’s circle for home care.",
    createdAt: "2026-09-02T08:12:00.000Z",
    read: false,
    inviteId: "inv-maya",
  }),
  createNotification({
    id: "n-invite-practitioner",
    type: NOTIFICATION_TYPES.PRACTITIONER_INVITATION,
    title: "Practitioner invitation",
    body: "Nurse Rivera was invited to Ellie’s clinical circle.",
    createdAt: "2026-09-02T08:14:00.000Z",
    read: true,
  }),
  createNotification({
    id: "n-invite-accepted",
    type: NOTIFICATION_TYPES.INVITATION_ACCEPTED,
    title: "Maya accepted the invitation",
    body: "Maya Chen is now an active caregiver on Ellie’s circle.",
    createdAt: "2026-09-01T16:20:00.000Z",
    read: true,
  }),
  createNotification({
    id: "n-invite-declined",
    type: NOTIFICATION_TYPES.INVITATION_DECLINED,
    title: "Invitation declined",
    body: "A weekend cover caregiver declined the invitation.",
    createdAt: "2026-08-30T14:10:00.000Z",
    read: true,
  }),
  createNotification({
    id: "n-joined",
    type: NOTIFICATION_TYPES.NEW_USER_JOINED,
    title: "Maya joined the household",
    body: "Maya Chen accepted and can now see Ellie’s schedule and tasks.",
    createdAt: "2026-09-01T16:21:00.000Z",
    read: false,
  }),
  createNotification({
    id: "n-sched-req",
    type: NOTIFICATION_TYPES.SCHEDULE_REQUEST,
    title: "Evening check-in requested",
    body: "Sarah requested tonight’s visit with Maya at 7:00 p.m.",
    createdAt: "2026-09-01T10:12:00.000Z",
    read: false,
    visitId: "visit-wed-evening",
  }),
  createNotification({
    id: "n-sched-ok",
    type: NOTIFICATION_TYPES.SCHEDULE_ACCEPTED,
    title: "Maya confirmed tonight’s check-in",
    body: "Evening visit is set for 7:00 p.m.",
    createdAt: "2026-09-01T10:42:00.000Z",
    read: false,
    visitId: "visit-wed-evening",
  }),
  createNotification({
    id: "n-sched-change",
    type: NOTIFICATION_TYPES.SCHEDULE_CHANGED,
    title: "Cardiology visit moved",
    body: "James is driving Ellie at 2:15 p.m. tomorrow.",
    createdAt: "2026-09-01T11:15:00.000Z",
    read: false,
  }),
  createNotification({
    id: "n-task",
    type: NOTIFICATION_TYPES.TASK_ASSIGNED,
    title: "Evening blood pressure assigned",
    body: "Maya has evening blood pressure and the afternoon walk on Ellie’s plan.",
    createdAt: "2026-09-02T07:10:00.000Z",
    read: false,
    taskId: "task-bp-eve",
  }),
  createNotification({
    id: "n-appt",
    type: NOTIFICATION_TYPES.APPOINTMENT_REMINDER,
    title: "Reminder · Cardiology visit",
    body: "Tomorrow · 2:15 p.m. · Dr. Patel",
    createdAt: "2026-09-01T11:16:00.000Z",
    read: false,
  }),
  createNotification({
    id: "n-med-1",
    type: NOTIFICATION_TYPES.MEDICATION_REMINDER,
    title: "Reminder · Lisinopril",
    body: "10mg · Once a day · 8:00 AM · Sarah Walsh. This is a care reminder, not medical advice.",
    createdAt: "2026-09-02T11:45:00.000Z",
    read: false,
    medicationId: "med-ellie-lisinopril",
  }),
  createNotification({
    id: "n-care",
    type: NOTIFICATION_TYPES.CARE_UPDATE,
    title: "Medication list updated",
    body: "Vitamin D was added to Ellie’s profile.",
    createdAt: "2026-08-31T18:05:00.000Z",
    read: true,
  }),
  createNotification({
    id: "n-alert",
    type: NOTIFICATION_TYPES.EMERGENCY_ALERT,
    title: "Care status needs the circle",
    body: "Maya recorded that Ellie was unwell after the morning visit. Open the dashboard.",
    createdAt: "2026-09-02T09:05:00.000Z",
    read: false,
  }),
  createNotification({
    id: "n-msg-1",
    type: NOTIFICATION_TYPES.MESSAGE,
    title: "Nurse Rivera sent a message",
    body: "No new concerns from Friday’s check. Keep the evening BP log going into Wednesday’s visit.",
    createdAt: "2026-09-01T16:41:00.000Z",
    read: false,
  }),
];

export const mockActivities = [
  createActivity({
    id: "a-today-in",
    seniorId: "senior-eleanor",
    kind: CARE_HISTORY_KINDS.CHECK_IN,
    type: ACTIVITY_TYPES.SCHEDULE,
    title: "Caregiver checked in",
    body: "Maya Chen arrived for morning personal care.",
    actor: "Maya Chen",
    actorId: "user-caregiver",
    occurredAt: stampAt(3, 9, 5),
    createdAt: stampAt(3, 9, 5),
    source: "visit",
    sourceId: "visit-wed-morning:check_in",
    relatedId: "visit-wed-morning",
  }),
  createActivity({
    id: "a-today-task",
    seniorId: "senior-eleanor",
    kind: CARE_HISTORY_KINDS.TASK,
    type: ACTIVITY_TYPES.CARE,
    title: "Morning medication completed",
    body: "Taken with tea. No rush.",
    actor: "Maya Chen",
    actorId: "user-caregiver",
    occurredAt: stampAt(3, 10, 30),
    createdAt: stampAt(3, 10, 30),
    source: "completion",
    sourceId: "done-ellie-meds-wed",
    relatedId: "task-ellie-meds-am",
  }),
  createActivity({
    id: "a-today-med",
    seniorId: "senior-eleanor",
    kind: CARE_HISTORY_KINDS.MEDICATION,
    type: ACTIVITY_TYPES.CARE,
    title: "Medication recorded",
    body: "Lisinopril 10mg was logged as taken · Morning dose with tea.",
    actor: "Maya Chen",
    actorId: "user-caregiver",
    occurredAt: stampAt(3, 11, 0),
    createdAt: stampAt(3, 11, 0),
    source: "dose",
    sourceId: "dose-lisinopril-wed",
    relatedId: "med-ellie-lisinopril",
  }),
  createActivity({
    id: "a-today-out",
    seniorId: "senior-eleanor",
    kind: CARE_HISTORY_KINDS.CHECK_OUT,
    type: ACTIVITY_TYPES.SCHEDULE,
    title: "Caregiver checked out",
    body: "Maya Chen finished morning personal care.",
    actor: "Maya Chen",
    actorId: "user-caregiver",
    occurredAt: stampAt(3, 12, 5),
    createdAt: stampAt(3, 12, 5),
    source: "visit",
    sourceId: "visit-wed-morning:check_out",
    relatedId: "visit-wed-morning",
  }),
  createActivity({
    id: "a1",
    seniorId: "senior-eleanor",
    kind: CARE_HISTORY_KINDS.CARE,
    type: ACTIVITY_TYPES.CARE,
    title: "Blood pressure recorded",
    body: "128/76 · in range for Ellie’s plan.",
    actor: "Maya Chen",
    createdAt: "2026-09-01T13:05:00.000Z",
  }),
  createActivity({
    id: "a2",
    seniorId: "senior-eleanor",
    kind: CARE_HISTORY_KINDS.TASK,
    type: ACTIVITY_TYPES.CARE,
    title: "Lunch and hydration completed",
    body: "Full meal, water taken with afternoon meds reminder set.",
    actor: "Maya Chen",
    createdAt: "2026-09-01T12:48:00.000Z",
  }),
  createActivity({
    id: "a3",
    seniorId: "senior-eleanor",
    kind: CARE_HISTORY_KINDS.SCHEDULE,
    type: ACTIVITY_TYPES.SCHEDULE,
    title: "Cardiology ride confirmed",
    body: "James will pick Ellie up at 1:30 p.m. on Wednesday.",
    actor: "James Walsh",
    createdAt: "2026-09-01T11:12:00.000Z",
  }),
  createActivity({
    id: "a4",
    seniorId: "senior-eleanor",
    kind: CARE_HISTORY_KINDS.CLINICAL,
    type: ACTIVITY_TYPES.CLINICAL,
    title: "Home health note added",
    body: "Nurse Rivera flagged no new concerns after yesterday’s visit.",
    actor: "Nurse Rivera",
    createdAt: "2026-08-31T16:25:00.000Z",
  }),
  createActivity({
    id: "a5",
    seniorId: "senior-eleanor",
    kind: CARE_HISTORY_KINDS.CIRCLE,
    type: ACTIVITY_TYPES.CIRCLE,
    title: "Vitamin D added to the record",
    body: "Sarah updated Ellie’s medication list.",
    actor: "Sarah Walsh",
    createdAt: "2026-08-31T18:06:00.000Z",
  }),
  createActivity({
    id: "a6",
    seniorId: "senior-eleanor",
    kind: CARE_HISTORY_KINDS.TASK,
    type: ACTIVITY_TYPES.CARE,
    title: "Monday walk completed",
    body: "Short loop around the block. Ellie was steady with the walker.",
    actor: "Maya Chen",
    createdAt: "2026-08-31T10:48:00.000Z",
  }),
  createActivity({
    id: "a7",
    seniorId: "senior-eleanor",
    kind: CARE_HISTORY_KINDS.CLINICAL,
    type: ACTIVITY_TYPES.CLINICAL,
    title: "BP plan confirmed",
    body: "Keep the evening log through Wednesday’s cardiology visit. No medication change.",
    actor: "Dr. Priya Patel",
    createdAt: "2026-09-01T17:10:00.000Z",
  }),
  createActivity({
    id: "a8",
    seniorId: "senior-eleanor",
    kind: CARE_HISTORY_KINDS.CARE,
    type: ACTIVITY_TYPES.CARE,
    title: "Care plan updated",
    body: "Daily support plan now includes evening blood pressure and the afternoon walk.",
    actor: "Sarah Walsh",
    createdAt: "2026-08-28T14:30:00.000Z",
  }),
];

export const mockDocuments = [
  createDocument({
    id: "doc-directive",
    seniorId: "senior-eleanor",
    title: "Advance directive",
    category: "legal",
    visibility: "family",
    status: "on_file",
    updatedAt: "2026-03-12T15:00:00.000Z",
    createdAt: "2026-03-12T15:00:00.000Z",
    notes: "Held by Sarah. Upload the signed copy to keep it in the vault.",
    uploadedByName: "Sarah Walsh",
  }),
  createDocument({
    id: "doc-insurance",
    seniorId: "senior-eleanor",
    title: "Medicare insurance card",
    category: "insurance",
    visibility: "circle",
    status: "on_file",
    updatedAt: "2026-01-04T10:00:00.000Z",
    createdAt: "2026-01-04T10:00:00.000Z",
    notes: "Member ID is on the card. The circle can open this at appointments.",
    uploadedByName: "Sarah Walsh",
  }),
  createDocument({
    id: "doc-meds",
    seniorId: "senior-eleanor",
    title: "Current medication list",
    category: "clinical",
    visibility: "clinical",
    status: "needs_review",
    updatedAt: "2026-08-31T18:06:00.000Z",
    createdAt: "2026-08-20T14:10:00.000Z",
    notes: "Updated when Vitamin D was added.",
    uploadedByName: "Dr. Priya Patel",
  }),
  createDocument({
    id: "doc-pharmacy",
    seniorId: "senior-eleanor",
    title: "Pharmacy printout",
    category: "clinical",
    visibility: "clinical",
    status: "on_file",
    updatedAt: "2026-08-20T14:10:00.000Z",
    createdAt: "2026-08-20T14:10:00.000Z",
    notes: "CVS on North Avenue.",
    uploadedByName: "Maya Chen",
  }),
];

const ELEANOR_CIRCLE_KEYS = [
  "user-family",
  "email:chidi@famielda.test",
  "user-caregiver",
  "email:rivera@famielda.test",
  "user-practitioner",
  "email:physio@famielda.test",
];
const ELEANOR_CIRCLE_IDS = ["user-family", "user-caregiver", "user-practitioner"];

export const mockConversations = [
  createConversation({
    id: "conv-circle-eleanor",
    seniorId: "senior-eleanor",
    type: CONVERSATION_TYPES.CIRCLE,
    pairKey: "circle:senior-eleanor",
    participantKeys: ELEANOR_CIRCLE_KEYS,
    participantIds: ELEANOR_CIRCLE_IDS,
    memberIds: ["m1", "m2", "m3", "m4", "m5", "m7"],
    title: "Household thread",
    lastMessageBody: "Pharmacy bag is by the kettle if anyone is heading out.",
    lastAuthorId: "user-family",
    lastAuthorKey: "user-family",
    lastAuthorName: "Sarah Walsh",
    lastMessageAt: "2026-09-01T17:05:00.000Z",
    readAtBy: {
      "user-family": "2026-09-01T17:06:00.000Z",
      "user-caregiver": "2026-09-01T17:10:00.000Z",
    },
    createdAt: "2026-08-20T09:00:00.000Z",
    updatedAt: "2026-09-01T17:05:00.000Z",
    createdBy: "user-family",
  }),
  createConversation({
    id: "conv-amina-maya",
    seniorId: "senior-eleanor",
    type: CONVERSATION_TYPES.DIRECT,
    pairKey: "direct:senior-eleanor:user-caregiver|user-family",
    participantKeys: ["user-caregiver", "user-family"],
    participantIds: ["user-caregiver", "user-family"],
    memberIds: ["m1", "m3"],
    title: "Maya Chen",
    lastMessageBody: "Yes — walk is on for 3:30. I’ll keep it short and bring water. BP was 128/76 this morning.",
    lastAuthorId: "user-caregiver",
    lastAuthorKey: "user-caregiver",
    lastAuthorName: "Maya Chen",
    lastMessageAt: "2026-09-01T09:28:00.000Z",
    readAtBy: { "user-family": "2026-09-01T09:40:00.000Z" },
    createdAt: "2026-09-01T09:12:00.000Z",
    updatedAt: "2026-09-01T09:28:00.000Z",
    createdBy: "user-family",
  }),
  createConversation({
    id: "conv-amina-rivera",
    seniorId: "senior-eleanor",
    type: CONVERSATION_TYPES.DIRECT,
    pairKey: "direct:senior-eleanor:email:rivera@famielda.test|user-family",
    participantKeys: ["email:rivera@famielda.test", "user-family"],
    participantIds: ["user-family"],
    memberIds: ["m1", "m4"],
    title: "Nurse Rivera",
    lastMessageBody: "No new concerns from Friday’s check. Keep the evening BP log going into Wednesday’s visit.",
    lastAuthorKey: "email:rivera@famielda.test",
    lastAuthorName: "Nurse Rivera",
    lastMessageAt: "2026-09-01T16:40:00.000Z",
    readAtBy: {},
    createdAt: "2026-09-01T16:40:00.000Z",
    updatedAt: "2026-09-01T16:40:00.000Z",
    createdBy: "email:rivera@famielda.test",
  }),
  createConversation({
    id: "conv-amina-patel",
    seniorId: "senior-eleanor",
    type: CONVERSATION_TYPES.DIRECT,
    pairKey: "direct:senior-eleanor:user-family|user-practitioner",
    participantKeys: ["user-family", "user-practitioner"],
    participantIds: ["user-family", "user-practitioner"],
    memberIds: ["m1", "m5"],
    title: "Dr. Priya Patel",
    lastMessageBody: "Wednesday’s cardiology note is on the record. Call if the evening BP climbs above 150.",
    lastAuthorId: "user-practitioner",
    lastAuthorKey: "user-practitioner",
    lastAuthorName: "Dr. Priya Patel",
    lastMessageAt: "2026-08-31T15:10:00.000Z",
    readAtBy: { "user-family": "2026-08-31T18:00:00.000Z" },
    createdAt: "2026-08-31T14:40:00.000Z",
    updatedAt: "2026-08-31T15:10:00.000Z",
    createdBy: "user-family",
  }),
  createConversation({
    id: "conv-amina-sam",
    seniorId: "senior-eleanor",
    type: CONVERSATION_TYPES.DIRECT,
    pairKey: "direct:senior-eleanor:email:physio@famielda.test|user-family",
    participantKeys: ["email:physio@famielda.test", "user-family"],
    participantIds: ["user-family"],
    memberIds: ["m1", "m7"],
    title: "Sam Okeke",
    lastMessageBody: "Thursday we’ll stay with chair strength if the garden path is warm. Keep the walker by the back door.",
    lastAuthorKey: "email:physio@famielda.test",
    lastAuthorName: "Sam Okeke",
    lastMessageAt: "2026-08-29T10:22:00.000Z",
    readAtBy: { "user-family": "2026-08-29T12:00:00.000Z" },
    createdAt: "2026-08-29T10:05:00.000Z",
    updatedAt: "2026-08-29T10:22:00.000Z",
    createdBy: "user-family",
  }),
];

export const mockMessages = [
  createMessage({
    id: "msg-circle-1",
    conversationId: "conv-circle-eleanor",
    seniorId: "senior-eleanor",
    type: CONVERSATION_TYPES.CIRCLE,
    authorId: "",
    authorKey: "email:chidi@famielda.test",
    author: "James Walsh",
    authorName: "James Walsh",
    role: "family",
    authorKind: "family",
    body: "I’ll be at the house at 1:30 Wednesday for cardiology. If the pharmacy bag is ready, I can drop it on the way back.",
    participantKeys: ELEANOR_CIRCLE_KEYS,
    participantIds: ELEANOR_CIRCLE_IDS,
    createdAt: "2026-09-01T11:18:00.000Z",
  }),
  createMessage({
    id: "msg-circle-2",
    conversationId: "conv-circle-eleanor",
    seniorId: "senior-eleanor",
    type: CONVERSATION_TYPES.CIRCLE,
    authorId: "user-family",
    authorKey: "user-family",
    author: "Sarah Walsh",
    authorName: "Sarah Walsh",
    role: "family",
    authorKind: "family",
    body: "Pharmacy bag is by the kettle if anyone is heading out.",
    participantKeys: ELEANOR_CIRCLE_KEYS,
    participantIds: ELEANOR_CIRCLE_IDS,
    createdAt: "2026-09-01T17:05:00.000Z",
  }),
  createMessage({
    id: "msg-maya-1",
    conversationId: "conv-amina-maya",
    seniorId: "senior-eleanor",
    type: CONVERSATION_TYPES.DIRECT,
    authorId: "user-family",
    authorKey: "user-family",
    author: "Sarah Walsh",
    authorName: "Sarah Walsh",
    role: "family",
    authorKind: "family",
    body: "Maya, can you confirm the afternoon walk still works? Ellie asked for the garden path if it is not too warm.",
    participantKeys: ["user-caregiver", "user-family"],
    participantIds: ["user-caregiver", "user-family"],
    createdAt: "2026-09-01T09:12:00.000Z",
  }),
  createMessage({
    id: "msg-maya-2",
    conversationId: "conv-amina-maya",
    seniorId: "senior-eleanor",
    type: CONVERSATION_TYPES.DIRECT,
    authorId: "user-caregiver",
    authorKey: "user-caregiver",
    author: "Maya Chen",
    authorName: "Maya Chen",
    role: "caregiver",
    authorKind: "caregiver",
    body: "Yes — walk is on for 3:30. I’ll keep it short and bring water. BP was 128/76 this morning.",
    participantKeys: ["user-caregiver", "user-family"],
    participantIds: ["user-caregiver", "user-family"],
    createdAt: "2026-09-01T09:28:00.000Z",
  }),
  createMessage({
    id: "msg-nurse-1",
    conversationId: "conv-amina-rivera",
    seniorId: "senior-eleanor",
    type: CONVERSATION_TYPES.DIRECT,
    authorKey: "email:rivera@famielda.test",
    author: "Nurse Rivera",
    authorName: "Nurse Rivera",
    role: "health_practitioner",
    authorKind: "practitioner",
    body: "No new concerns from Friday’s check. Keep the evening BP log going into Wednesday’s visit.",
    participantKeys: ["email:rivera@famielda.test", "user-family"],
    participantIds: ["user-family"],
    createdAt: "2026-09-01T16:40:00.000Z",
  }),
  createMessage({
    id: "msg-md-1",
    conversationId: "conv-amina-patel",
    seniorId: "senior-eleanor",
    type: CONVERSATION_TYPES.DIRECT,
    authorId: "user-family",
    authorKey: "user-family",
    author: "Sarah Walsh",
    authorName: "Sarah Walsh",
    role: "family",
    authorKind: "family",
    body: "Dr. Patel — Ellie has been a little dizzy after supper. Should we hold the evening walk if BP is high?",
    participantKeys: ["user-family", "user-practitioner"],
    participantIds: ["user-family", "user-practitioner"],
    createdAt: "2026-08-31T14:40:00.000Z",
  }),
  createMessage({
    id: "msg-md-2",
    conversationId: "conv-amina-patel",
    seniorId: "senior-eleanor",
    type: CONVERSATION_TYPES.DIRECT,
    authorId: "user-practitioner",
    authorKey: "user-practitioner",
    author: "Dr. Priya Patel",
    authorName: "Dr. Priya Patel",
    role: "health_practitioner",
    authorKind: "practitioner",
    body: "Wednesday’s cardiology note is on the record. Call if the evening BP climbs above 150.",
    participantKeys: ["user-family", "user-practitioner"],
    participantIds: ["user-family", "user-practitioner"],
    createdAt: "2026-08-31T15:10:00.000Z",
  }),
  createMessage({
    id: "msg-physio-1",
    conversationId: "conv-amina-sam",
    seniorId: "senior-eleanor",
    type: CONVERSATION_TYPES.DIRECT,
    authorId: "user-family",
    authorKey: "user-family",
    author: "Sarah Walsh",
    authorName: "Sarah Walsh",
    role: "family",
    authorKind: "family",
    body: "Sam, the garden path is Ellie’s favorite. Can Thursday stay short if it is humid?",
    participantKeys: ["email:physio@famielda.test", "user-family"],
    participantIds: ["user-family"],
    createdAt: "2026-08-29T10:05:00.000Z",
  }),
  createMessage({
    id: "msg-physio-2",
    conversationId: "conv-amina-sam",
    seniorId: "senior-eleanor",
    type: CONVERSATION_TYPES.DIRECT,
    authorKey: "email:physio@famielda.test",
    author: "Sam Okeke",
    authorName: "Sam Okeke",
    role: "health_practitioner",
    authorKind: "practitioner",
    body: "Thursday we’ll stay with chair strength if the garden path is warm. Keep the walker by the back door.",
    participantKeys: ["email:physio@famielda.test", "user-family"],
    participantIds: ["user-family"],
    createdAt: "2026-08-29T10:22:00.000Z",
  }),
];
